AWSTemplateFormatVersion: 2010-09-09
Resources:
  MIDSERVER:
    Type: 'AWS::EC2::Instance'
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: ami-08bd00d7713a39e7d
      InstanceType: t2.micro
      KeyName: ITOM
      Monitoring: 'false'
      Tags:
        - Key: Environment
          Value: Dev
        - Key: Name
          Value: MID SERVER
        - Key: Tier
          Value: '1'
      NetworkInterfaces:
        - DeleteOnTermination: 'true'
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId: subnet-03695f2f73344d5bd
          PrivateIpAddresses:
            - PrivateIpAddress: 192.0.59.237
              Primary: 'true'
          GroupSet:
            - !Ref sgCentOS7x8664withUpdatesHVM190101AutogenByAWSMP3
          AssociatePublicIpAddress: 'true'
  s3zipfilerepos:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
  sgCentOS7x8664withUpdatesHVM190101AutogenByAWSMP3:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: >-
        This security group was generated by AWS Marketplace and is based on
        recommended settings for CentOS 7 (x86_64) - with Updates HVM version
        1901_01 provided by Centos.org
      VpcId: vpc-0b3f20a73a2c14f92
  ingress3:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sgCentOS7x8664withUpdatesHVM190101AutogenByAWSMP3
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
  egress3:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      GroupId: !Ref sgCentOS7x8664withUpdatesHVM190101AutogenByAWSMP3
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
Description: EC2Instance-CFTemplate
